services:
  develop:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
      target: devcontainer
    volumes:
      - ../:/workspace
      - colcon_build:/workspace/build
      - colcon_install:/workspace/install
      - colcon_log:/workspace/log
    stdin_open: true
    tty: true
    ports:
      - '5173:5173'
    networks:
      - ros_net
    environment:
      - ROS_DOMAIN_ID=10
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FRE_INFORMATION_PANEL_BRIDGE_ENDPOINT=/capability

volumes:
  colcon_build:
  colcon_install:
  colcon_log:

networks:
  ros_net:
